# Generated by Django 4.0.5 on 2023-07-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('hobby', models.TextField()),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
    ]
